spring:
  application:
    name: dear-comrade-security-zero-to-hero
  datasource:
    url: jdbc:postgresql://172.21.0.2:5432/dha
    username: comrade
    password: dear
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org:
      springframework:
        security: debug



