spring:
  application:
    name: dear-comrade-security-zero-to-hero
logging:
  level:
    org:
      springframework:
        security: debug


reactjs:
  web:
    base-url: http://localhost:5173
    path: '/**'
    methods: DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT
  security:
    secret-key: dhaasajsjajsjashajsjajsashawueu8wue8uuwuiwejwnj3848348723723723878329490
    expiration-duration: 120000
    token-header: Authorization
    token-prefix: "Bearer "
